import { RootCategory, CategoryFlatItem } from "@/lib/types/category";

export const initialRootCategories: RootCategory[] = [
  {
    id: "root-rtw",
    name: "Ready-To-Wear",
    slug: "ready-to-wear",
    code: "RTW",
    description: "Mainline apparel, tailoring, outerwear, and seasonal knitwear.",
    displayOrder: 1,
    status: "active",
    createdAt: "2026-01-10T10:00:00Z",
    updatedAt: "2026-02-15T14:30:00Z",
    categories: [
      {
        id: "cat-outerwear",
        rootCategoryId: "root-rtw",
        name: "Outerwear",
        slug: "outerwear",
        code: "OTR",
        description: "Cashmere coats, wool overcoats, trench coats, and parkas.",
        displayOrder: 1,
        status: "active",
        createdAt: "2026-01-11T11:00:00Z",
        updatedAt: "2026-02-15T14:30:00Z",
        subcategories: [
          {
            id: "sub-overcoats",
            categoryId: "cat-outerwear",
            rootCategoryId: "root-rtw",
            name: "Overcoats & Trench",
            slug: "overcoats-trench",
            code: "OTR-OVC",
            description: "Double-breasted and belted luxury wool coats.",
            displayOrder: 1,
            status: "active",
            productCount: 14,
            createdAt: "2026-01-12T12:00:00Z",
            updatedAt: "2026-02-15T14:30:00Z",
          },
          {
            id: "sub-blazers",
            categoryId: "cat-outerwear",
            rootCategoryId: "root-rtw",
            name: "Tailored Blazers",
            slug: "tailored-blazers",
            code: "OTR-BLZ",
            description: "Structured and relaxed wool/silk jackets.",
            displayOrder: 2,
            status: "active",
            productCount: 22,
            createdAt: "2026-01-12T12:00:00Z",
            updatedAt: "2026-02-15T14:30:00Z",
          },
          {
            id: "sub-shearling",
            categoryId: "cat-outerwear",
            rootCategoryId: "root-rtw",
            name: "Shearling & Leather",
            slug: "shearling-leather",
            code: "OTR-SHR",
            description: "Handcrafted shearling bombers and leather jackets.",
            displayOrder: 3,
            status: "inactive",
            productCount: 6,
            createdAt: "2026-01-12T12:00:00Z",
            updatedAt: "2026-02-20T09:15:00Z",
          },
        ],
      },
      {
        id: "cat-knitwear",
        rootCategoryId: "root-rtw",
        name: "Knitwear",
        slug: "knitwear",
        code: "KNT",
        description: "Fine gauge merino, chunky cashmere, and ribbed cardigans.",
        displayOrder: 2,
        status: "active",
        createdAt: "2026-01-11T11:00:00Z",
        updatedAt: "2026-02-15T14:30:00Z",
        subcategories: [
          {
            id: "sub-cashmere-crew",
            categoryId: "cat-knitwear",
            rootCategoryId: "root-rtw",
            name: "Cashmere Crewnecks",
            slug: "cashmere-crewnecks",
            code: "KNT-CRW",
            description: "100% grade-A Mongolian cashmere sweaters.",
            displayOrder: 1,
            status: "active",
            productCount: 18,
            createdAt: "2026-01-12T12:00:00Z",
            updatedAt: "2026-02-15T14:30:00Z",
          },
          {
            id: "sub-cardigans",
            categoryId: "cat-knitwear",
            rootCategoryId: "root-rtw",
            name: "Draped Cardigans",
            slug: "draped-cardigans",
            code: "KNT-CRD",
            description: "Relaxed open and horn-buttoned knit cardigans.",
            displayOrder: 2,
            status: "active",
            productCount: 11,
            createdAt: "2026-01-12T12:00:00Z",
            updatedAt: "2026-02-15T14:30:00Z",
          },
        ],
      },
      {
        id: "cat-trousers",
        rootCategoryId: "root-rtw",
        name: "Trousers & Denim",
        slug: "trousers-denim",
        code: "TRS",
        description: "Pleated wool trousers, relaxed chinos, and raw denim.",
        displayOrder: 3,
        status: "active",
        createdAt: "2026-01-11T11:00:00Z",
        updatedAt: "2026-02-15T14:30:00Z",
        subcategories: [
          {
            id: "sub-pleated-trousers",
            categoryId: "cat-trousers",
            rootCategoryId: "root-rtw",
            name: "Wide-Leg Pleated Trousers",
            slug: "wide-leg-pleated-trousers",
            code: "TRS-PLT",
            description: "High-rise virgin wool tailored trousers.",
            displayOrder: 1,
            status: "active",
            productCount: 16,
            createdAt: "2026-01-12T12:00:00Z",
            updatedAt: "2026-02-15T14:30:00Z",
          },
          {
            id: "sub-selvedge-denim",
            categoryId: "cat-trousers",
            rootCategoryId: "root-rtw",
            name: "Japanese Selvedge Denim",
            slug: "japanese-selvedge-denim",
            code: "TRS-SLV",
            description: "13.5oz shuttle-loom raw selvedge jeans.",
            displayOrder: 2,
            status: "active",
            productCount: 9,
            createdAt: "2026-01-12T12:00:00Z",
            updatedAt: "2026-02-15T14:30:00Z",
          },
        ],
      },
    ],
  },
  {
    id: "root-ftw",
    name: "Footwear",
    slug: "footwear",
    code: "FTW",
    description: "Handcrafted Italian leather boots, loafers, and minimal sneakers.",
    displayOrder: 2,
    status: "active",
    createdAt: "2026-01-10T10:00:00Z",
    updatedAt: "2026-02-15T14:30:00Z",
    categories: [
      {
        id: "cat-boots",
        rootCategoryId: "root-ftw",
        name: "Boots",
        slug: "boots",
        code: "BTS",
        description: "Chelsea, zip, and combat boots.",
        displayOrder: 1,
        status: "active",
        createdAt: "2026-01-11T11:00:00Z",
        updatedAt: "2026-02-15T14:30:00Z",
        subcategories: [
          {
            id: "sub-chelsea-boots",
            categoryId: "cat-boots",
            rootCategoryId: "root-ftw",
            name: "Calfskin Chelsea Boots",
            slug: "calfskin-chelsea-boots",
            code: "BTS-CHL",
            description: "Blake-stitched Italian calfskin with crepe/leather soles.",
            displayOrder: 1,
            status: "active",
            productCount: 8,
            createdAt: "2026-01-12T12:00:00Z",
            updatedAt: "2026-02-15T14:30:00Z",
          },
        ],
      },
      {
        id: "cat-loafers",
        rootCategoryId: "root-ftw",
        name: "Loafers & Derbies",
        slug: "loafers-derbies",
        code: "LFR",
        description: "Penny loafers and Goodyear-welted derbies.",
        displayOrder: 2,
        status: "active",
        createdAt: "2026-01-11T11:00:00Z",
        updatedAt: "2026-02-15T14:30:00Z",
        subcategories: [
          {
            id: "sub-penny-loafers",
            categoryId: "cat-loafers",
            rootCategoryId: "root-ftw",
            name: "Chunky Penny Loafers",
            slug: "chunky-penny-loafers",
            code: "LFR-PNY",
            description: "Polished smooth leather with lugged rubber soles.",
            displayOrder: 1,
            status: "active",
            productCount: 12,
            createdAt: "2026-01-12T12:00:00Z",
            updatedAt: "2026-02-15T14:30:00Z",
          },
        ],
      },
    ],
  },
  {
    id: "root-acc",
    name: "Leather Goods & Accessories",
    slug: "accessories",
    code: "ACC",
    description: "Tote bags, crossbody bags, small leather goods, and eyewear.",
    displayOrder: 3,
    status: "active",
    createdAt: "2026-01-10T10:00:00Z",
    updatedAt: "2026-02-15T14:30:00Z",
    categories: [
      {
        id: "cat-bags",
        rootCategoryId: "root-acc",
        name: "Bags & Totes",
        slug: "bags-totes",
        code: "BAG",
        description: "Full-grain leather totes and architectural shoulder bags.",
        displayOrder: 1,
        status: "active",
        createdAt: "2026-01-11T11:00:00Z",
        updatedAt: "2026-02-15T14:30:00Z",
        subcategories: [
          {
            id: "sub-leather-totes",
            categoryId: "cat-bags",
            rootCategoryId: "root-acc",
            name: "Structured Studio Totes",
            slug: "structured-studio-totes",
            code: "BAG-TOT",
            description: "Vegetable-tanned leather everyday tote bags.",
            displayOrder: 1,
            status: "active",
            productCount: 7,
            createdAt: "2026-01-12T12:00:00Z",
            updatedAt: "2026-02-15T14:30:00Z",
          },
        ],
      },
    ],
  },
  {
    id: "root-archive",
    name: "Runway & Archive",
    slug: "runway-archive",
    code: "ARC",
    description: "Limited edition runway showpieces and private archive releases.",
    displayOrder: 4,
    status: "inactive",
    createdAt: "2026-01-10T10:00:00Z",
    updatedAt: "2026-02-15T14:30:00Z",
    categories: [],
  },
];

export function flattenHierarchy(data: RootCategory[]): CategoryFlatItem[] {
  const result: CategoryFlatItem[] = [];

  data.forEach((root) => {
    result.push({
      id: root.id,
      name: root.name,
      slug: root.slug,
      code: root.code,
      level: "root",
      displayOrder: root.displayOrder,
      status: root.status,
      itemCount: root.categories.length,
      createdAt: root.createdAt,
      updatedAt: root.updatedAt,
    });

    root.categories.forEach((cat) => {
      result.push({
        id: cat.id,
        name: cat.name,
        slug: cat.slug,
        code: cat.code,
        level: "category",
        parentName: root.name,
        parentId: root.id,
        rootName: root.name,
        rootId: root.id,
        displayOrder: cat.displayOrder,
        status: cat.status,
        itemCount: cat.subcategories.length,
        createdAt: cat.createdAt,
        updatedAt: cat.updatedAt,
      });

      cat.subcategories.forEach((sub) => {
        result.push({
          id: sub.id,
          name: sub.name,
          slug: sub.slug,
          code: sub.code,
          level: "subcategory",
          parentName: cat.name,
          parentId: cat.id,
          rootName: root.name,
          rootId: root.id,
          displayOrder: sub.displayOrder,
          status: sub.status,
          itemCount: sub.productCount,
          createdAt: sub.createdAt,
          updatedAt: sub.updatedAt,
        });
      });
    });
  });

  return result;
}
