import { RootCategory, CategoryFlatItem } from "@/lib/types/category";

export const initialRootCategories: RootCategory[] = [
  {
    id: "root-rtw",
    name: "Ready-To-Wear",
    slug: "ready-to-wear",
    code: "RTW",
    description: "Mainline apparel, tailoring, outerwear, and seasonal knitwear.",
    imageUrl: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=600&auto=format&fit=crop",
    bannerUrl: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=1200&auto=format&fit=crop",
    displayOrder: 1,
    status: "active",
    createdAt: "2026-01-10T10:00:00Z",
    updatedAt: "2026-02-15T14:30:00Z",
    categories: [
      {
        id: "cat-outerwear",
        rootCategoryId: "root-rtw",
        name: "Outerwear",
        slug: "outerwear",
        code: "OTR",
        description: "Cashmere coats, wool overcoats, trench coats, and parkas.",
        imageUrl: "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?q=80&w=600&auto=format&fit=crop",
        bannerUrl: "https://images.unsplash.com/photo-1544441893-675973e31985?q=80&w=1200&auto=format&fit=crop",
        displayOrder: 1,
        status: "active",
        createdAt: "2026-01-11T11:00:00Z",
        updatedAt: "2026-02-15T14:30:00Z",
        subcategories: [
          {
            id: "sub-overcoats",
            categoryId: "cat-outerwear",
            rootCategoryId: "root-rtw",
            name: "Overcoats & Trench",
            slug: "overcoats-trench",
            code: "OTR-OVC",
            description: "Double-breasted and belted luxury wool coats.",
            imageUrl: "https://images.unsplash.com/photo-1548883354-7622d03aca27?q=80&w=600&auto=format&fit=crop",
            displayOrder: 1,
            status: "active",
            productCount: 14,
            createdAt: "2026-01-12T12:00:00Z",
            updatedAt: "2026-02-15T14:30:00Z",
          },
          {
            id: "sub-blazers",
            categoryId: "cat-outerwear",
            rootCategoryId: "root-rtw",
            name: "Tailored Blazers",
            slug: "tailored-blazers",
            code: "OTR-BLZ",
            description: "Structured and relaxed wool/silk jackets.",
            imageUrl: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?q=80&w=600&auto=format&fit=crop",
            displayOrder: 2,
            status: "active",
            productCount: 22,
            createdAt: "2026-01-12T12:00:00Z",
            updatedAt: "2026-02-15T14:30:00Z",
          },
          {
            id: "sub-shearling",
            categoryId: "cat-outerwear",
            rootCategoryId: "root-rtw",
            name: "Shearling & Leather",
            slug: "shearling-leather",
            code: "OTR-SHR",
            description: "Handcrafted shearling bombers and leather jackets.",
            imageUrl: "https://images.unsplash.com/photo-1521223890158-f9f7c3d5d504?q=80&w=600&auto=format&fit=crop",
            displayOrder: 3,
            status: "inactive",
            productCount: 6,
            createdAt: "2026-01-12T12:00:00Z",
            updatedAt: "2026-02-20T09:15:00Z",
          },
        ],
      },
      {
        id: "cat-knitwear",
        rootCategoryId: "root-rtw",
        name: "Knitwear",
        slug: "knitwear",
        code: "KNT",
        description: "Fine gauge merino, chunky cashmere, and ribbed cardigans.",
        imageUrl: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?q=80&w=600&auto=format&fit=crop",
        bannerUrl: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?q=80&w=1200&auto=format&fit=crop",
        displayOrder: 2,
        status: "active",
        createdAt: "2026-01-11T11:00:00Z",
        updatedAt: "2026-02-15T14:30:00Z",
        subcategories: [
          {
            id: "sub-cashmere-crew",
            categoryId: "cat-knitwear",
            rootCategoryId: "root-rtw",
            name: "Cashmere Crewnecks",
            slug: "cashmere-crewnecks",
            code: "KNT-CRW",
            description: "100% grade-A Mongolian cashmere sweaters.",
            imageUrl: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?q=80&w=600&auto=format&fit=crop",
            displayOrder: 1,
            status: "active",
            productCount: 18,
            createdAt: "2026-01-12T12:00:00Z",
            updatedAt: "2026-02-15T14:30:00Z",
          },
          {
            id: "sub-cardigans",
            categoryId: "cat-knitwear",
            rootCategoryId: "root-rtw",
            name: "Merino Cardigans",
            slug: "merino-cardigans",
            code: "KNT-CRD",
            description: "Buttoned fine gauge merino cardigans.",
            imageUrl: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?q=80&w=600&auto=format&fit=crop",
            displayOrder: 2,
            status: "active",
            productCount: 12,
            createdAt: "2026-01-12T12:00:00Z",
            updatedAt: "2026-02-15T14:30:00Z",
          },
          {
            id: "sub-turtlenecks",
            categoryId: "cat-knitwear",
            rootCategoryId: "root-rtw",
            name: "Rollnecks & Turtlenecks",
            slug: "rollnecks-turtlenecks",
            code: "KNT-TRT",
            description: "Ribbed seamless wool and cashmere rollnecks.",
            imageUrl: "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?q=80&w=600&auto=format&fit=crop",
            displayOrder: 3,
            status: "active",
            productCount: 9,
            createdAt: "2026-01-12T12:00:00Z",
            updatedAt: "2026-02-15T14:30:00Z",
          },
        ],
      },
      {
        id: "cat-tailoring",
        rootCategoryId: "root-rtw",
        name: "Tailored Trousers & Suits",
        slug: "tailored-trousers-suits",
        code: "TLS",
        description: "Pleated wide-leg trousers and bespoke tailoring sets.",
        imageUrl: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=600&auto=format&fit=crop",
        bannerUrl: "https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?q=80&w=1200&auto=format&fit=crop",
        displayOrder: 3,
        status: "active",
        createdAt: "2026-01-11T11:00:00Z",
        updatedAt: "2026-02-15T14:30:00Z",
        subcategories: [
          {
            id: "sub-wide-trousers",
            categoryId: "cat-tailoring",
            rootCategoryId: "root-rtw",
            name: "Wide-Leg Wool Trousers",
            slug: "wide-leg-wool-trousers",
            code: "TLS-WID",
            description: "High-waisted pleated wool gabardine trousers.",
            imageUrl: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?q=80&w=600&auto=format&fit=crop",
            displayOrder: 1,
            status: "active",
            productCount: 16,
            createdAt: "2026-01-12T12:00:00Z",
            updatedAt: "2026-02-15T14:30:00Z",
          },
        ],
      },
    ],
  },
  {
    id: "root-ftw",
    name: "Footwear",
    slug: "footwear",
    code: "FTW",
    description: "Handmade Italian leather boots, loafers, and runway sneakers.",
    imageUrl: "https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=600&auto=format&fit=crop",
    bannerUrl: "https://images.unsplash.com/photo-1449505278894-297fdb3edbc1?q=80&w=1200&auto=format&fit=crop",
    displayOrder: 2,
    status: "active",
    createdAt: "2026-01-10T10:00:00Z",
    updatedAt: "2026-02-15T14:30:00Z",
    categories: [
      {
        id: "cat-boots",
        rootCategoryId: "root-ftw",
        name: "Boots",
        slug: "boots",
        code: "BTS",
        description: "Chelsea boots, combat boots, and zipped ankle silhouettes.",
        imageUrl: "https://images.unsplash.com/photo-1608256246200-53e635b5b65f?q=80&w=600&auto=format&fit=crop",
        displayOrder: 1,
        status: "active",
        createdAt: "2026-01-11T11:00:00Z",
        updatedAt: "2026-02-15T14:30:00Z",
        subcategories: [
          {
            id: "sub-chelsea",
            categoryId: "cat-boots",
            rootCategoryId: "root-ftw",
            name: "Calfskin Chelsea Boots",
            slug: "calfskin-chelsea-boots",
            code: "BTS-CLS",
            description: "Goodyear welted Tuscan calfskin boots.",
            imageUrl: "https://images.unsplash.com/photo-1638247025967-b4e38f787b76?q=80&w=600&auto=format&fit=crop",
            displayOrder: 1,
            status: "active",
            productCount: 8,
            createdAt: "2026-01-12T12:00:00Z",
            updatedAt: "2026-02-15T14:30:00Z",
          },
        ],
      },
      {
        id: "cat-sneakers",
        rootCategoryId: "root-ftw",
        name: "Luxury Sneakers",
        slug: "luxury-sneakers",
        code: "SNK",
        description: "Minimalist leather court shoes and technical runners.",
        imageUrl: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?q=80&w=600&auto=format&fit=crop",
        displayOrder: 2,
        status: "active",
        createdAt: "2026-01-11T11:00:00Z",
        updatedAt: "2026-02-15T14:30:00Z",
        subcategories: [
          {
            id: "sub-court",
            categoryId: "cat-sneakers",
            rootCategoryId: "root-ftw",
            name: "Low-Top Court Sneakers",
            slug: "low-top-court-sneakers",
            code: "SNK-CRT",
            description: "Monochrome full-grain nappa sneakers.",
            imageUrl: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?q=80&w=600&auto=format&fit=crop",
            displayOrder: 1,
            status: "active",
            productCount: 11,
            createdAt: "2026-01-12T12:00:00Z",
            updatedAt: "2026-02-15T14:30:00Z",
          },
        ],
      },
    ],
  },
  {
    id: "root-acc",
    name: "Leather Goods & Accessories",
    slug: "leather-goods-accessories",
    code: "ACC",
    description: "Totes, structured crossbody bags, wallets, and silk scarves.",
    imageUrl: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=600&auto=format&fit=crop",
    bannerUrl: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=1200&auto=format&fit=crop",
    displayOrder: 3,
    status: "active",
    createdAt: "2026-01-10T10:00:00Z",
    updatedAt: "2026-02-15T14:30:00Z",
    categories: [
      {
        id: "cat-bags",
        rootCategoryId: "root-acc",
        name: "Handbags & Totes",
        slug: "handbags-totes",
        code: "BAG",
        description: "Pebbled calfskin totes and architectural shoulder bags.",
        imageUrl: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?q=80&w=600&auto=format&fit=crop",
        displayOrder: 1,
        status: "active",
        createdAt: "2026-01-11T11:00:00Z",
        updatedAt: "2026-02-15T14:30:00Z",
        subcategories: [
          {
            id: "sub-totes",
            categoryId: "cat-bags",
            rootCategoryId: "root-acc",
            name: "Structured Studio Totes",
            slug: "structured-studio-totes",
            code: "BAG-TOT",
            description: "Unlined double-face leather shopper totes.",
            imageUrl: "https://images.unsplash.com/photo-1591561954557-26941169b49e?q=80&w=600&auto=format&fit=crop",
            displayOrder: 1,
            status: "active",
            productCount: 7,
            createdAt: "2026-01-12T12:00:00Z",
            updatedAt: "2026-02-15T14:30:00Z",
          },
        ],
      },
    ],
  },
  {
    id: "root-arc",
    name: "Runway & Archive",
    slug: "runway-archive",
    code: "ARC",
    description: "One-off editorial runway pieces and historical couture archives.",
    imageUrl: "https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=600&auto=format&fit=crop",
    bannerUrl: "https://images.unsplash.com/photo-1469334031218-e382a71b716b?q=80&w=1200&auto=format&fit=crop",
    displayOrder: 4,
    status: "inactive",
    createdAt: "2026-01-10T10:00:00Z",
    updatedAt: "2026-02-20T09:15:00Z",
    categories: [],
  },
];

export function flattenHierarchy(rootCategories: RootCategory[]): CategoryFlatItem[] {
  const result: CategoryFlatItem[] = [];

  rootCategories.forEach((root) => {
    result.push({
      id: root.id,
      name: root.name,
      slug: root.slug,
      code: root.code,
      level: "root",
      imageUrl: root.imageUrl,
      bannerUrl: root.bannerUrl,
      description: root.description,
      displayOrder: root.displayOrder,
      status: root.status,
      itemCount: root.categories.length,
      createdAt: root.createdAt,
      updatedAt: root.updatedAt,
    });

    root.categories.forEach((cat) => {
      result.push({
        id: cat.id,
        name: cat.name,
        slug: cat.slug,
        code: cat.code,
        level: "category",
        imageUrl: cat.imageUrl,
        bannerUrl: cat.bannerUrl,
        description: cat.description,
        parentName: root.name,
        parentId: root.id,
        rootName: root.name,
        rootId: root.id,
        displayOrder: cat.displayOrder,
        status: cat.status,
        itemCount: cat.subcategories.length,
        createdAt: cat.createdAt,
        updatedAt: cat.updatedAt,
      });

      cat.subcategories.forEach((sub) => {
        result.push({
          id: sub.id,
          name: sub.name,
          slug: sub.slug,
          code: sub.code,
          level: "subcategory",
          imageUrl: sub.imageUrl,
          bannerUrl: sub.bannerUrl,
          description: sub.description,
          parentName: cat.name,
          parentId: cat.id,
          rootName: root.name,
          rootId: root.id,
          displayOrder: sub.displayOrder,
          status: sub.status,
          itemCount: sub.productCount,
          createdAt: sub.createdAt,
          updatedAt: sub.updatedAt,
        });
      });
    });
  });

  return result;
}
