import { InventoryLocation, InventoryBalance, InventoryTransaction } from "@/lib/types/inventory";
import { Batch, Serial } from "@/lib/types/tracking";

export const initialInventoryLocations: InventoryLocation[] = [
  // 1. Central Warehouse & Sub-locations
  {
    id: "loc-wh-01",
    code: "LOC-WH-CENTRAL",
    name: "Tejgaon Central Hub (Warehouse)",
    type: "WAREHOUSE",
    warehouseId: "wh-01",
    warehouseName: "Central Fulfillment Hub",
    isInventoryEnabled: true,
    isSellable: true,
    isReceivingLocation: false,
    isQuarantineLocation: false,
    isDamageLocation: false,
    status: "active",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "loc-wh-01-rcv",
    code: "LOC-WH-CENTRAL-RCV",
    name: "Tejgaon Receiving Dock A",
    type: "RECEIVING",
    warehouseId: "wh-01",
    warehouseName: "Central Fulfillment Hub",
    parentLocationId: "loc-wh-01",
    parentLocationName: "Tejgaon Central Hub",
    isInventoryEnabled: true,
    isSellable: false,
    isReceivingLocation: true,
    isQuarantineLocation: false,
    isDamageLocation: false,
    status: "active",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "loc-wh-01-sh-a01",
    code: "LOC-WH-SH-A01",
    name: "Rack A-01 (Outerwear & Suits)",
    type: "SHELF",
    warehouseId: "wh-01",
    warehouseName: "Central Fulfillment Hub",
    parentLocationId: "loc-wh-01",
    parentLocationName: "Tejgaon Central Hub",
    zone: "Zone A",
    aisle: "Aisle 01",
    rack: "Rack 01",
    shelf: "Shelf A",
    isInventoryEnabled: true,
    isSellable: true,
    isReceivingLocation: false,
    isQuarantineLocation: false,
    isDamageLocation: false,
    status: "active",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "loc-wh-01-sh-b02",
    code: "LOC-WH-SH-B02",
    name: "Rack B-02 (Silk & Luxury Fabrics)",
    type: "SHELF",
    warehouseId: "wh-01",
    warehouseName: "Central Fulfillment Hub",
    parentLocationId: "loc-wh-01",
    parentLocationName: "Tejgaon Central Hub",
    zone: "Zone B",
    aisle: "Aisle 02",
    rack: "Rack 02",
    shelf: "Shelf B",
    isInventoryEnabled: true,
    isSellable: true,
    isReceivingLocation: false,
    isQuarantineLocation: false,
    isDamageLocation: false,
    status: "active",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "loc-wh-01-qc",
    code: "LOC-WH-CENTRAL-QC",
    name: "Central QA / Fabric Inspection Station",
    type: "QC",
    warehouseId: "wh-01",
    warehouseName: "Central Fulfillment Hub",
    parentLocationId: "loc-wh-01",
    parentLocationName: "Tejgaon Central Hub",
    isInventoryEnabled: true,
    isSellable: false,
    isReceivingLocation: false,
    isQuarantineLocation: false,
    isDamageLocation: false,
    status: "active",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "loc-wh-01-dmg",
    code: "LOC-WH-CENTRAL-DMG",
    name: "Central Damaged / Defect Holding Area",
    type: "DAMAGE",
    warehouseId: "wh-01",
    warehouseName: "Central Fulfillment Hub",
    parentLocationId: "loc-wh-01",
    parentLocationName: "Tejgaon Central Hub",
    isInventoryEnabled: true,
    isSellable: false,
    isReceivingLocation: false,
    isQuarantineLocation: false,
    isDamageLocation: true,
    status: "active",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },

  // 2. Secondary Warehouse
  {
    id: "loc-wh-02",
    code: "LOC-WH-CHATTOGRAM",
    name: "Agrabad Regional Depot (Warehouse)",
    type: "WAREHOUSE",
    warehouseId: "wh-02",
    warehouseName: "Chittagong Port Logistics",
    isInventoryEnabled: true,
    isSellable: true,
    isReceivingLocation: false,
    isQuarantineLocation: false,
    isDamageLocation: false,
    status: "active",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },

  // 3. Retail Stores & Store Locations
  {
    id: "loc-str-01",
    code: "LOC-STR-GULSHAN",
    name: "Gulshan Flagship Avenue (Store)",
    type: "STORE",
    storeId: "str-01",
    storeName: "Gulshan Flagship Avenue",
    isInventoryEnabled: true,
    isSellable: true,
    isReceivingLocation: false,
    isQuarantineLocation: false,
    isDamageLocation: false,
    status: "active",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "loc-str-01-flr",
    code: "LOC-STR-GLS-FLR",
    name: "Gulshan Flagship Main Floor",
    type: "STORE_FLOOR",
    storeId: "str-01",
    storeName: "Gulshan Flagship Avenue",
    parentLocationId: "loc-str-01",
    parentLocationName: "Gulshan Flagship Avenue",
    isInventoryEnabled: true,
    isSellable: true,
    isReceivingLocation: false,
    isQuarantineLocation: false,
    isDamageLocation: false,
    status: "active",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "loc-str-01-bck",
    code: "LOC-STR-GLS-BCK",
    name: "Gulshan Flagship Stock Backroom",
    type: "STORE_BACKROOM",
    storeId: "str-01",
    storeName: "Gulshan Flagship Avenue",
    parentLocationId: "loc-str-01",
    parentLocationName: "Gulshan Flagship Avenue",
    isInventoryEnabled: true,
    isSellable: true,
    isReceivingLocation: false,
    isQuarantineLocation: false,
    isDamageLocation: false,
    status: "active",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "loc-str-02",
    code: "LOC-STR-BANANI",
    name: "Banani Boutique 11 (Store)",
    type: "STORE",
    storeId: "str-02",
    storeName: "Banani 11 Studio",
    isInventoryEnabled: true,
    isSellable: true,
    isReceivingLocation: false,
    isQuarantineLocation: false,
    isDamageLocation: false,
    status: "active",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "loc-str-03",
    code: "LOC-STR-DHANMONDI",
    name: "Dhanmondi 27 Gallery (Store)",
    type: "STORE",
    storeId: "str-03",
    storeName: "Dhanmondi 27 Gallery",
    isInventoryEnabled: true,
    isSellable: true,
    isReceivingLocation: false,
    isQuarantineLocation: false,
    isDamageLocation: false,
    status: "active",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },

  // 4. In-Transit Global Holding Location
  {
    id: "loc-transit-global",
    code: "LOC-IN-TRANSIT",
    name: "Global Fleet Logistics In-Transit Pipeline",
    type: "IN_TRANSIT",
    isInventoryEnabled: true,
    isSellable: false,
    isReceivingLocation: false,
    isQuarantineLocation: false,
    isDamageLocation: false,
    status: "active",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
];

export const initialBatches: Batch[] = [
  {
    id: "bat-001",
    batchNumber: "BAT-2026-001",
    supplierBatchNo: "SUP-TEX-8821",
    productId: "prod-001",
    productName: "Italian Wool Overcoat",
    variantId: "var-001-1",
    variantName: "Noir Black / 40R",
    sku: "NC-OW-OVC-BLK-40",
    initialQuantity: 100,
    currentQuantity: 85,
    mfgDate: "2025-11-15",
    expiryDate: "2028-11-15",
    receivedDate: "2026-01-10",
    status: "ACTIVE",
    notes: "Super 150s Merino Wool lot with water-repellent finish.",
    createdAt: "2026-01-10T10:00:00.000Z",
    updatedAt: "2026-01-10T10:00:00.000Z",
  },
  {
    id: "bat-002",
    batchNumber: "BAT-2026-002",
    supplierBatchNo: "SUP-SILK-9002",
    productId: "prod-002",
    productName: "Mulberry Silk Evening Blouse",
    variantId: "var-002-1",
    variantName: "Champagne Pearl / Small",
    sku: "NC-TP-BLS-PRL-S",
    initialQuantity: 60,
    currentQuantity: 45,
    mfgDate: "2025-12-01",
    receivedDate: "2026-01-15",
    status: "ACTIVE",
    notes: "100% Grade 6A Mulberry Silk 22 Momme.",
    createdAt: "2026-01-15T12:00:00.000Z",
    updatedAt: "2026-01-15T12:00:00.000Z",
  },
];

export const initialSerials: Serial[] = [
  {
    id: "ser-001",
    serialNumber: "SN-NC-2026-000101",
    productId: "prod-001",
    productName: "Italian Wool Overcoat",
    variantId: "var-001-1",
    variantName: "Noir Black / 40R",
    sku: "NC-OW-OVC-BLK-40",
    currentLocationId: "loc-wh-01-sh-a01",
    currentLocationCode: "LOC-WH-SH-A01",
    currentLocationName: "Rack A-01 (Outerwear & Suits)",
    batchId: "bat-001",
    batchNumber: "BAT-2026-001",
    status: "AVAILABLE",
    receivedDate: "2026-01-10",
    createdAt: "2026-01-10T10:00:00.000Z",
    updatedAt: "2026-01-10T10:00:00.000Z",
  },
  {
    id: "ser-002",
    serialNumber: "SN-NC-2026-000102",
    productId: "prod-001",
    productName: "Italian Wool Overcoat",
    variantId: "var-001-1",
    variantName: "Noir Black / 40R",
    sku: "NC-OW-OVC-BLK-40",
    currentLocationId: "loc-str-01-flr",
    currentLocationCode: "LOC-STR-GLS-FLR",
    currentLocationName: "Gulshan Flagship Main Floor",
    batchId: "bat-001",
    batchNumber: "BAT-2026-001",
    status: "AVAILABLE",
    receivedDate: "2026-01-12",
    createdAt: "2026-01-12T14:00:00.000Z",
    updatedAt: "2026-01-12T14:00:00.000Z",
  },
];

export const initialInventoryBalances: InventoryBalance[] = [
  // 1. Central Warehouse - Shelf A01 (Italian Wool Overcoat Noir 40R)
  {
    id: "bal-001",
    locationId: "loc-wh-01-sh-a01",
    locationCode: "LOC-WH-SH-A01",
    locationName: "Rack A-01 (Outerwear & Suits)",
    locationType: "SHELF",
    warehouseId: "wh-01",
    warehouseName: "Central Fulfillment Hub",
    productId: "prod-001",
    productName: "Italian Wool Overcoat",
    productCode: "OTR-OVC-001",
    variantId: "var-001-1",
    variantName: "Noir Black / 40R",
    sku: "NC-OW-OVC-BLK-40",
    barcode: "894100100101",
    unitCost: 18500,
    retailPrice: 38500,
    categoryName: "Overcoats & Outerwear",
    brandName: "NCloth Sartorial",
    onHand: 120,
    reserved: 20,
    available: 100,
    inTransit: 0,
    quarantined: 0,
    damaged: 0,
    minStockLevel: 25,
    maxStockLevel: 200,
    reorderPoint: 40,
    updatedAt: "2026-01-20T10:00:00.000Z",
  },
  // 2. Central Warehouse - Shelf A01 (Italian Wool Overcoat Camel 42R)
  {
    id: "bal-002",
    locationId: "loc-wh-01-sh-a01",
    locationCode: "LOC-WH-SH-A01",
    locationName: "Rack A-01 (Outerwear & Suits)",
    locationType: "SHELF",
    warehouseId: "wh-01",
    warehouseName: "Central Fulfillment Hub",
    productId: "prod-001",
    productName: "Italian Wool Overcoat",
    productCode: "OTR-OVC-001",
    variantId: "var-001-2",
    variantName: "Camel Heather / 42R",
    sku: "NC-OW-OVC-CML-42",
    barcode: "894100100102",
    unitCost: 18500,
    retailPrice: 38500,
    categoryName: "Overcoats & Outerwear",
    brandName: "NCloth Sartorial",
    onHand: 75,
    reserved: 10,
    available: 65,
    inTransit: 0,
    quarantined: 0,
    damaged: 0,
    minStockLevel: 15,
    maxStockLevel: 150,
    reorderPoint: 30,
    updatedAt: "2026-01-20T10:00:00.000Z",
  },
  // 3. Central Warehouse - Shelf B02 (Mulberry Silk Evening Blouse Pearl S)
  {
    id: "bal-003",
    locationId: "loc-wh-01-sh-b02",
    locationCode: "LOC-WH-SH-B02",
    locationName: "Rack B-02 (Silk & Luxury Fabrics)",
    locationType: "SHELF",
    warehouseId: "wh-01",
    warehouseName: "Central Fulfillment Hub",
    productId: "prod-002",
    productName: "Mulberry Silk Evening Blouse",
    productCode: "TP-BLS-002",
    variantId: "var-002-1",
    variantName: "Champagne Pearl / Small",
    sku: "NC-TP-BLS-PRL-S",
    barcode: "894100200101",
    unitCost: 4500,
    retailPrice: 12500,
    categoryName: "Blouses & Silk Tops",
    brandName: "NCloth Studio",
    onHand: 80,
    reserved: 0,
    available: 80,
    inTransit: 0,
    quarantined: 0,
    damaged: 0,
    minStockLevel: 20,
    maxStockLevel: 120,
    reorderPoint: 35,
    updatedAt: "2026-01-20T10:00:00.000Z",
  },
  // 4. Gulshan Flagship Store - Floor Display (Italian Wool Overcoat Noir 40R)
  {
    id: "bal-004",
    locationId: "loc-str-01-flr",
    locationCode: "LOC-STR-GLS-FLR",
    locationName: "Gulshan Flagship Main Floor",
    locationType: "STORE_FLOOR",
    storeId: "str-01",
    storeName: "Gulshan Flagship Avenue",
    productId: "prod-001",
    productName: "Italian Wool Overcoat",
    productCode: "OTR-OVC-001",
    variantId: "var-001-1",
    variantName: "Noir Black / 40R",
    sku: "NC-OW-OVC-BLK-40",
    barcode: "894100100101",
    unitCost: 18500,
    retailPrice: 38500,
    categoryName: "Overcoats & Outerwear",
    brandName: "NCloth Sartorial",
    onHand: 14,
    reserved: 2,
    available: 12,
    inTransit: 0,
    quarantined: 0,
    damaged: 0,
    minStockLevel: 5,
    maxStockLevel: 30,
    reorderPoint: 8,
    updatedAt: "2026-01-20T10:00:00.000Z",
  },
  // 5. Banani Boutique 11 - Store Stock (Mulberry Silk Blouse Pearl S)
  {
    id: "bal-005",
    locationId: "loc-str-02",
    locationCode: "LOC-STR-BANANI",
    locationName: "Banani Boutique 11 (Store)",
    locationType: "STORE",
    storeId: "str-02",
    storeName: "Banani 11 Studio",
    productId: "prod-002",
    productName: "Mulberry Silk Evening Blouse",
    productCode: "TP-BLS-002",
    variantId: "var-002-1",
    variantName: "Champagne Pearl / Small",
    sku: "NC-TP-BLS-PRL-S",
    barcode: "894100200101",
    unitCost: 4500,
    retailPrice: 12500,
    categoryName: "Blouses & Silk Tops",
    brandName: "NCloth Studio",
    onHand: 4,
    reserved: 0,
    available: 4,
    inTransit: 0,
    quarantined: 0,
    damaged: 0,
    minStockLevel: 5,
    maxStockLevel: 25,
    reorderPoint: 6,
    updatedAt: "2026-01-20T10:00:00.000Z",
  },
  // 6. In-Transit Balance (30 units moving from Central WH to Banani)
  {
    id: "bal-006",
    locationId: "loc-transit-global",
    locationCode: "LOC-IN-TRANSIT",
    locationName: "Global Fleet Logistics In-Transit Pipeline",
    locationType: "IN_TRANSIT",
    productId: "prod-001",
    productName: "Italian Wool Overcoat",
    productCode: "OTR-OVC-001",
    variantId: "var-001-1",
    variantName: "Noir Black / 40R",
    sku: "NC-OW-OVC-BLK-40",
    barcode: "894100100101",
    unitCost: 18500,
    retailPrice: 38500,
    categoryName: "Overcoats & Outerwear",
    brandName: "NCloth Sartorial",
    onHand: 30,
    reserved: 0,
    available: 0,
    inTransit: 30,
    quarantined: 0,
    damaged: 0,
    updatedAt: "2026-01-20T10:00:00.000Z",
  },
  // 7. Defect / Damaged Holding Area
  {
    id: "bal-007",
    locationId: "loc-wh-01-dmg",
    locationCode: "LOC-WH-CENTRAL-DMG",
    locationName: "Central Damaged / Defect Holding Area",
    locationType: "DAMAGE",
    warehouseId: "wh-01",
    warehouseName: "Central Fulfillment Hub",
    productId: "prod-001",
    productName: "Italian Wool Overcoat",
    productCode: "OTR-OVC-001",
    variantId: "var-001-1",
    variantName: "Noir Black / 40R",
    sku: "NC-OW-OVC-BLK-40",
    barcode: "894100100101",
    unitCost: 18500,
    retailPrice: 38500,
    categoryName: "Overcoats & Outerwear",
    brandName: "NCloth Sartorial",
    onHand: 2,
    reserved: 0,
    available: 0,
    inTransit: 0,
    quarantined: 0,
    damaged: 2,
    updatedAt: "2026-01-20T10:00:00.000Z",
  },
];

export const initialInventoryTransactions: InventoryTransaction[] = [
  {
    id: "txn-001",
    txnNumber: "INV-TXN-2026-000001",
    type: "PURCHASE_RECEIPT",
    productId: "prod-001",
    productName: "Italian Wool Overcoat",
    variantId: "var-001-1",
    variantName: "Noir Black / 40R",
    sku: "NC-OW-OVC-BLK-40",
    quantity: 150,
    unitCost: 18500,
    totalCost: 2775000,
    destinationLocationId: "loc-wh-01-rcv",
    destinationLocationCode: "LOC-WH-CENTRAL-RCV",
    destinationLocationName: "Tejgaon Receiving Dock A",
    referenceType: "PURCHASE_ORDER",
    referenceId: "po-001",
    referenceNumber: "PO-2026-000001",
    createdBy: "Alexander S. (Admin)",
    createdAt: "2026-01-10T10:15:00.000Z",
  },
  {
    id: "txn-002",
    txnNumber: "INV-TXN-2026-000002",
    type: "PUTAWAY",
    productId: "prod-001",
    productName: "Italian Wool Overcoat",
    variantId: "var-001-1",
    variantName: "Noir Black / 40R",
    sku: "NC-OW-OVC-BLK-40",
    quantity: 150,
    unitCost: 18500,
    totalCost: 2775000,
    sourceLocationId: "loc-wh-01-rcv",
    sourceLocationCode: "LOC-WH-CENTRAL-RCV",
    sourceLocationName: "Tejgaon Receiving Dock A",
    destinationLocationId: "loc-wh-01-sh-a01",
    destinationLocationCode: "LOC-WH-SH-A01",
    destinationLocationName: "Rack A-01 (Outerwear & Suits)",
    referenceType: "PUTAWAY_TASK",
    referenceId: "ptw-001",
    referenceNumber: "PTW-2026-000001",
    createdBy: "WMS Putaway Operator",
    createdAt: "2026-01-10T11:30:00.000Z",
  },
  {
    id: "txn-003",
    txnNumber: "INV-TXN-2026-000003",
    type: "TRANSFER_DISPATCH",
    productId: "prod-001",
    productName: "Italian Wool Overcoat",
    variantId: "var-001-1",
    variantName: "Noir Black / 40R",
    sku: "NC-OW-OVC-BLK-40",
    quantity: 30,
    unitCost: 18500,
    totalCost: 555000,
    sourceLocationId: "loc-wh-01-sh-a01",
    sourceLocationCode: "LOC-WH-SH-A01",
    sourceLocationName: "Rack A-01 (Outerwear & Suits)",
    destinationLocationId: "loc-transit-global",
    destinationLocationCode: "LOC-IN-TRANSIT",
    destinationLocationName: "Global Fleet Logistics In-Transit Pipeline",
    referenceType: "STOCK_TRANSFER",
    referenceId: "st-001",
    referenceNumber: "ST-2026-000001",
    createdBy: "Central Warehouse Dispatcher",
    createdAt: "2026-01-18T09:00:00.000Z",
  },
];
