import { Product } from "@/lib/types/product";

export const initialProducts: Product[] = [
  {
    id: "prod-01",
    name: "Double-Breasted Cashmere Trench Coat",
    code: "OTR-OVC-001",
    slug: "double-breasted-cashmere-trench-coat",
    categoryId: "sub-overcoats",
    categoryName: "Overcoats & Trench",
    brandId: "brand-saint-laurent",
    brandName: "Saint Laurent Rive Gauche",
    attributeSetId: "set-fashion",
    attributeSetName: "Fashion & Apparel",
    productType: "STOCKABLE",
    description: "Hand-tailored double-breasted trench coat crafted from 100% pure Mongolian cashmere. Features horn buttons, belted waist, and cupro silk lining.",
    status: "active",
    defaultCostPrice: 650,
    defaultSellingPrice: 1850,
    compareAtPrice: 2200,
    currency: "EUR",
    hasVariants: true,
    variantAttributeIds: ["attr-color", "attr-size"],
    attributes: [
      {
        attributeId: "attr-material",
        attributeCode: "material_fabric",
        attributeName: "Material / Fabric",
        value: "val-mat-01",
      },
      {
        attributeId: "attr-weight",
        attributeCode: "product_weight",
        attributeName: "Weight Spec",
        value: 1.45,
        unitId: "unit-kg",
        unitSymbol: "kg",
      },
      {
        attributeId: "attr-warranty",
        attributeCode: "warranty_period",
        attributeName: "Warranty Period",
        value: "Lifetime Atelier Repair Service",
      },
    ],
    variants: [
      {
        id: "var-01-01",
        name: "Noir Black / S",
        sku: "OTR-OVC-001-BLK-S",
        barcode: "3700123456701",
        combination: { "attr-color": "val-col-01", "attr-size": "val-sz-02" },
        costPrice: 650,
        sellingPrice: 1850,
        compareAtPrice: 2200,
        weight: 1.4,
        status: "active",
        imageUrl: "https://images.unsplash.com/photo-1544441893-675973e31985?q=80&w=600&auto=format&fit=crop",
      },
      {
        id: "var-01-02",
        name: "Noir Black / M",
        sku: "OTR-OVC-001-BLK-M",
        barcode: "3700123456702",
        combination: { "attr-color": "val-col-01", "attr-size": "val-sz-03" },
        costPrice: 650,
        sellingPrice: 1850,
        compareAtPrice: 2200,
        weight: 1.45,
        status: "active",
        imageUrl: "https://images.unsplash.com/photo-1544441893-675973e31985?q=80&w=600&auto=format&fit=crop",
      },
      {
        id: "var-01-03",
        name: "Noir Black / L",
        sku: "OTR-OVC-001-BLK-L",
        barcode: "3700123456703",
        combination: { "attr-color": "val-col-01", "attr-size": "val-sz-04" },
        costPrice: 650,
        sellingPrice: 1850,
        compareAtPrice: 2200,
        weight: 1.5,
        status: "active",
        imageUrl: "https://images.unsplash.com/photo-1544441893-675973e31985?q=80&w=600&auto=format&fit=crop",
      },
      {
        id: "var-01-04",
        name: "Camel Melange / S",
        sku: "OTR-OVC-001-CML-S",
        barcode: "3700123456704",
        combination: { "attr-color": "val-col-06", "attr-size": "val-sz-02" },
        costPrice: 650,
        sellingPrice: 1850,
        compareAtPrice: 2200,
        weight: 1.4,
        status: "active",
        imageUrl: "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?q=80&w=600&auto=format&fit=crop",
      },
      {
        id: "var-01-05",
        name: "Camel Melange / M",
        sku: "OTR-OVC-001-CML-M",
        barcode: "3700123456705",
        combination: { "attr-color": "val-col-06", "attr-size": "val-sz-03" },
        costPrice: 650,
        sellingPrice: 1850,
        compareAtPrice: 2200,
        weight: 1.45,
        status: "active",
        imageUrl: "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?q=80&w=600&auto=format&fit=crop",
      },
      {
        id: "var-01-06",
        name: "Camel Melange / L",
        sku: "OTR-OVC-001-CML-L",
        barcode: "3700123456706",
        combination: { "attr-color": "val-col-06", "attr-size": "val-sz-04" },
        costPrice: 650,
        sellingPrice: 1850,
        compareAtPrice: 2200,
        weight: 1.5,
        status: "active",
        imageUrl: "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?q=80&w=600&auto=format&fit=crop",
      },
    ],
    media: [
      {
        id: "med-01",
        url: "https://images.unsplash.com/photo-1544441893-675973e31985?q=80&w=800&auto=format&fit=crop",
        isPrimary: true,
        alt: "Double-Breasted Cashmere Trench Coat - Front View",
        sortOrder: 1,
      },
      {
        id: "med-02",
        url: "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?q=80&w=800&auto=format&fit=crop",
        isPrimary: false,
        alt: "Camel Colorway Detail",
        sortOrder: 2,
      },
    ],
    additionalInfo: {
      manufacturer: "Atelier Saint-Honoré Paris",
      originCountry: "France",
      warranty: "Lifetime Guarantee",
      hsCode: "6101.90.00",
      notes: "SS26 Runway Edition. Certified 100% traceable cashmere fleece.",
    },
    createdAt: "2026-01-15T09:00:00.000Z",
    updatedAt: "2026-02-20T14:30:00.000Z",
  },
  {
    id: "prod-02",
    name: "Chunky Ribbed Cashmere Crewneck",
    code: "KNT-CRW-002",
    slug: "chunky-ribbed-cashmere-crewneck",
    categoryId: "sub-cashmere-crew",
    categoryName: "Cashmere Crewnecks",
    brandId: "brand-loropiana",
    brandName: "Loro Piana",
    attributeSetId: "set-fashion",
    attributeSetName: "Fashion & Apparel",
    productType: "STOCKABLE",
    description: "7-gauge fisherman knit sweater spun from pure un-dyed organic cashmere yarns with relaxed dropped shoulders.",
    status: "active",
    defaultCostPrice: 320,
    defaultSellingPrice: 890,
    compareAtPrice: 1100,
    currency: "EUR",
    hasVariants: true,
    variantAttributeIds: ["attr-color", "attr-size"],
    attributes: [
      {
        attributeId: "attr-material",
        attributeCode: "material_fabric",
        attributeName: "Material / Fabric",
        value: "val-mat-01",
      },
      {
        attributeId: "attr-weight",
        attributeCode: "product_weight",
        attributeName: "Weight Spec",
        value: 0.65,
        unitId: "unit-kg",
        unitSymbol: "kg",
      },
    ],
    variants: [
      {
        id: "var-02-01",
        name: "Chalk White / S",
        sku: "KNT-CRW-002-WHT-S",
        barcode: "3700123456801",
        combination: { "attr-color": "val-col-02", "attr-size": "val-sz-02" },
        costPrice: 320,
        sellingPrice: 890,
        weight: 0.62,
        status: "active",
        imageUrl: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?q=80&w=600&auto=format&fit=crop",
      },
      {
        id: "var-02-02",
        name: "Chalk White / M",
        sku: "KNT-CRW-002-WHT-M",
        barcode: "3700123456802",
        combination: { "attr-color": "val-col-02", "attr-size": "val-sz-03" },
        costPrice: 320,
        sellingPrice: 890,
        weight: 0.65,
        status: "active",
        imageUrl: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?q=80&w=600&auto=format&fit=crop",
      },
      {
        id: "var-02-03",
        name: "Midnight Navy / M",
        sku: "KNT-CRW-002-NVY-M",
        barcode: "3700123456803",
        combination: { "attr-color": "val-col-03", "attr-size": "val-sz-03" },
        costPrice: 320,
        sellingPrice: 890,
        weight: 0.65,
        status: "active",
        imageUrl: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?q=80&w=600&auto=format&fit=crop",
      },
    ],
    media: [
      {
        id: "med-03",
        url: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?q=80&w=800&auto=format&fit=crop",
        isPrimary: true,
        alt: "Chalk White Cashmere Crewneck",
        sortOrder: 1,
      },
    ],
    additionalInfo: {
      manufacturer: "Loro Piana Mills Quarona",
      originCountry: "Italy",
      warranty: "2 Years Premium",
      hsCode: "6110.12.00",
    },
    createdAt: "2026-01-20T11:00:00.000Z",
    updatedAt: "2026-02-22T16:00:00.000Z",
  },
  {
    id: "prod-03",
    name: "Architectural Minimalist Desk Lamp",
    code: "FUR-LMP-003",
    slug: "architectural-minimalist-desk-lamp",
    categoryId: "cat-outerwear",
    categoryName: "Living & Office Furniture",
    brandId: "brand-acne",
    brandName: "Acne Studios",
    attributeSetId: "set-furniture",
    attributeSetName: "Living & Office Furniture",
    productType: "STOCKABLE",
    description: "Precision-machined titanium desk lamp with dimmable LED warm-spectrum light bar and integrated Qi wireless charging plate.",
    status: "active",
    defaultCostPrice: 110,
    defaultSellingPrice: 280,
    compareAtPrice: 350,
    currency: "EUR",
    hasVariants: false,
    variantAttributeIds: [],
    attributes: [
      {
        attributeId: "attr-material",
        attributeCode: "material_fabric",
        attributeName: "Material / Fabric",
        value: "val-mat-05",
      },
      {
        attributeId: "attr-weight",
        attributeCode: "product_weight",
        attributeName: "Weight Spec",
        value: 2.1,
        unitId: "unit-kg",
        unitSymbol: "kg",
      },
      {
        attributeId: "attr-warranty",
        attributeCode: "warranty_period",
        attributeName: "Warranty Period",
        value: "5 Years Manufacturer Warranty",
      },
    ],
    variants: [
      {
        id: "var-03-01",
        name: "Standard Edition",
        sku: "FUR-LMP-003-STD",
        barcode: "3700123456901",
        combination: {},
        costPrice: 110,
        sellingPrice: 280,
        compareAtPrice: 350,
        weight: 2.1,
        status: "active",
        imageUrl: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?q=80&w=600&auto=format&fit=crop",
      },
    ],
    media: [
      {
        id: "med-04",
        url: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?q=80&w=800&auto=format&fit=crop",
        isPrimary: true,
        alt: "Architectural Desk Lamp",
        sortOrder: 1,
      },
    ],
    additionalInfo: {
      manufacturer: "Nordic Precision Labs",
      originCountry: "Sweden",
      warranty: "5 Years Warranty",
      hsCode: "9405.20.00",
    },
    createdAt: "2026-02-01T14:00:00.000Z",
    updatedAt: "2026-02-24T10:00:00.000Z",
  },
];
