import { StoreShelf } from "@/lib/types/store-shelf";

export const initialStoreShelves: StoreShelf[] = [
  {
    id: "str-sh-par-01",
    name: "Runway Showcase Rack A1",
    code: "STR-PAR-RK01",
    storeId: "str-par-01",
    storeName: "Paris Flagship Boutique",
    zone: "Window Display",
    description: "Front display rack featuring SS26 outerwear, trench coats, and tailoring.",
    status: "active",
    itemCount: 24,
    createdAt: "2026-01-10T09:00:00.000Z",
    updatedAt: "2026-02-15T11:30:00.000Z",
  },
  {
    id: "str-sh-par-02",
    name: "VIP Private Salon Wardrobe",
    code: "STR-PAR-RK02",
    storeId: "str-par-01",
    storeName: "Paris Flagship Boutique",
    zone: "VIP Lounge",
    description: "Exclusive fitting wardrobe for private client appointments and custom orders.",
    status: "active",
    itemCount: 16,
    createdAt: "2026-01-10T09:30:00.000Z",
    updatedAt: "2026-02-18T14:15:00.000Z",
  },
  {
    id: "str-sh-dhk-01",
    name: "Main Floor Apparel Island",
    code: "STR-DHK-RK01",
    storeId: "str-dhk-01",
    storeName: "Dhaka Gulshan Boutique & Showroom",
    zone: "Sales Floor",
    description: "Central island rack for ready-to-wear tops, trousers, and light layering.",
    status: "active",
    itemCount: 48,
    createdAt: "2026-01-12T10:00:00.000Z",
    updatedAt: "2026-02-20T16:00:00.000Z",
  },
  {
    id: "str-sh-dhk-02",
    name: "Leather Goods Display Tower",
    code: "STR-DHK-RK02",
    storeId: "str-dhk-01",
    storeName: "Dhaka Gulshan Boutique & Showroom",
    zone: "Accessories Island",
    description: "Illuminated glass shelving unit for handbags, wallets, and silk scarves.",
    status: "active",
    itemCount: 32,
    createdAt: "2026-01-12T10:30:00.000Z",
    updatedAt: "2026-02-21T09:45:00.000Z",
  },
  {
    id: "str-sh-nyc-01",
    name: "SoHo Runway Focus Rack",
    code: "STR-NYC-RK01",
    storeId: "str-nyc-01",
    storeName: "Manhattan SoHo Flagship Store",
    zone: "Sales Floor",
    description: "High-traffic entrance rack highlighting newly arrived editorial collections.",
    status: "active",
    itemCount: 36,
    createdAt: "2026-01-14T11:00:00.000Z",
    updatedAt: "2026-02-22T13:20:00.000Z",
  },
  {
    id: "str-sh-mil-01",
    name: "Footwear Gallery Pedestal",
    code: "STR-MIL-RK01",
    storeId: "str-mil-02",
    storeName: "Milan Via Montenapoleone Boutique",
    zone: "Accessories Island",
    description: "Architectural stone plinth display for handmade Italian calfskin footwear.",
    status: "active",
    itemCount: 20,
    createdAt: "2026-01-16T12:00:00.000Z",
    updatedAt: "2026-02-23T15:10:00.000Z",
  },
  {
    id: "str-sh-ldn-01",
    name: "Bond Street Tailoring Bay",
    code: "STR-LDN-RK01",
    storeId: "str-ldn-03",
    storeName: "London New Bond Street Salon",
    zone: "Sales Floor",
    description: "Bespoke suiting and cashmere overcoats presentation wall.",
    status: "active",
    itemCount: 28,
    createdAt: "2026-01-18T13:00:00.000Z",
    updatedAt: "2026-02-24T10:00:00.000Z",
  },
  {
    id: "str-sh-tyo-01",
    name: "Ginza Archive Capsule Shelf",
    code: "STR-TYO-RK01",
    storeId: "str-tyo-04",
    storeName: "Tokyo Ginza Store & Private Lounge",
    zone: "Backroom Stock",
    description: "Backroom inventory shelf currently offline during salon renovation.",
    status: "inactive",
    itemCount: 0,
    createdAt: "2026-01-22T14:00:00.000Z",
    updatedAt: "2026-02-25T17:00:00.000Z",
  },
];
